# permissions for end users to view imagepolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: imagepolicy-viewer-role
rules:
- apiGroups:
  - image.toolkit.fluxcd.io
  resources:
  - imagepolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - image.toolkit.fluxcd.io
  resources:
  - imagepolicies/status
  verbs:
  - get
